language: rust

after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc &&
  echo '<meta http-equiv=refresh content=0;url=url/index.html>' > target/doc/index.html &&
  cp github.png target/doc/ &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -f https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages

env:
  - secure: DoxnyDvhhRocCKtvyRe0Wa4P/zwhEcSH67kSa1f+KMuLzZQqIxFqCGTha2KzKyuymMMVyUC1Is+MWzVjBtAaIHCm07Do/TH9rWijTZx0pWK9bJ8idxzycGTsZJEyzDQbkpGNRsAfygxwP2r+K6VSE6MDg2M6AjnSLzpjWMLqr+s=
